# coding: utf-8

"""
    SendPost API

    SendPost API to send transactional emails reliably  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@sendx.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.accountrecipient_api import AccountrecipientApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountrecipientApi(unittest.TestCase):
    """AccountrecipientApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.accountrecipient_api.AccountrecipientApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_recipient_router_get_all_messages_for_a_recipient(self):
        """Test case for recipient_router_get_all_messages_for_a_recipient

        """
        pass

    def test_recipient_router_get_all_messages_for_a_recipient_from_a_node(self):
        """Test case for recipient_router_get_all_messages_for_a_recipient_from_a_node

        """
        pass


if __name__ == '__main__':
    unittest.main()
