# coding: utf-8

"""
    SendPost API

    SendPost API to send transactional emails reliably  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@sendx.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.accountevent_api import AccounteventApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccounteventApi(unittest.TestCase):
    """AccounteventApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.accountevent_api.AccounteventApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_event_router_count_all_events_from_a_account_for_a_given_time_range(self):
        """Test case for event_router_count_all_events_from_a_account_for_a_given_time_range

        """
        pass

    def test_event_router_count_all_events_from_a_node_of_a_sub_account_for_a_given_time_range(self):
        """Test case for event_router_count_all_events_from_a_node_of_a_sub_account_for_a_given_time_range

        """
        pass

    def test_event_router_get(self):
        """Test case for event_router_get

        """
        pass

    def test_event_router_get_all_event_timestamp_keys_of_a_sub_account_from_a_specific_node_for_a_given_time_range(self):
        """Test case for event_router_get_all_event_timestamp_keys_of_a_sub_account_from_a_specific_node_for_a_given_time_range

        """
        pass

    def test_event_router_get_all_events_of_a_account_from_a_specific_node(self):
        """Test case for event_router_get_all_events_of_a_account_from_a_specific_node

        """
        pass

    def test_event_router_get_event_in_node(self):
        """Test case for event_router_get_event_in_node

        """
        pass


if __name__ == '__main__':
    unittest.main()
