# coding: utf-8

"""
    SendPost API

    SendPost API to send transactional emails reliably  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@sendx.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.models_suppression_email import ModelsSuppressionEmail  # noqa: E501
from swagger_client.rest import ApiException


class TestModelsSuppressionEmail(unittest.TestCase):
    """ModelsSuppressionEmail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelsSuppressionEmail(self):
        """Test ModelsSuppressionEmail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.models_suppression_email.ModelsSuppressionEmail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
