# coding: utf-8

"""
    SendPost API

    SendPost API to send transactional emails reliably  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@sendx.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.models_back_off_trigger import ModelsBackOffTrigger  # noqa: E501
from swagger_client.rest import ApiException


class TestModelsBackOffTrigger(unittest.TestCase):
    """ModelsBackOffTrigger unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelsBackOffTrigger(self):
        """Test ModelsBackOffTrigger"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.models_back_off_trigger.ModelsBackOffTrigger()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
