# coding: utf-8

"""
    SendPost API

    SendPost API to send transactional emails reliably  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@sendx.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.accounttag_api import AccounttagApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccounttagApi(unittest.TestCase):
    """AccounttagApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.accounttag_api.AccounttagApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tag_router_create(self):
        """Test case for tag_router_create

        """
        pass

    def test_tag_router_delete(self):
        """Test case for tag_router_delete

        """
        pass

    def test_tag_router_get_all(self):
        """Test case for tag_router_get_all

        """
        pass


if __name__ == '__main__':
    unittest.main()
