# coding: utf-8

"""
    SendPost API

    SendPost API to send transactional emails reliably  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@sendx.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.accountstat_api import AccountstatApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountstatApi(unittest.TestCase):
    """AccountstatApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.accountstat_api.AccountstatApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_account_stat_router_get_all_account_stats(self):
        """Test case for account_stat_router_get_all_account_stats

        """
        pass

    def test_account_stat_router_get_all_account_stats_by_group(self):
        """Test case for account_stat_router_get_all_account_stats_by_group

        """
        pass

    def test_account_stat_router_get_all_aggregate_account_stats(self):
        """Test case for account_stat_router_get_all_aggregate_account_stats

        """
        pass

    def test_account_stat_router_get_all_aggregate_account_stats_by_group(self):
        """Test case for account_stat_router_get_all_aggregate_account_stats_by_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
