# coding: utf-8

"""
    SendPost API

    SendPost API to send transactional emails reliably  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@sendx.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.editor_api import EditorApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEditorApi(unittest.TestCase):
    """EditorApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.editor_api.EditorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_editor_api_router_get_token(self):
        """Test case for editor_api_router_get_token

        """
        pass


if __name__ == '__main__':
    unittest.main()
