# coding: utf-8

"""
    SendPost API

    SendPost API to send transactional emails reliably  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@sendx.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.accountpayment_api import AccountpaymentApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountpaymentApi(unittest.TestCase):
    """AccountpaymentApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.accountpayment_api.AccountpaymentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_payment_router_create_customer_portal(self):
        """Test case for payment_router_create_customer_portal

        """
        pass

    def test_payment_router_create_payment_subscription(self):
        """Test case for payment_router_create_payment_subscription

        """
        pass

    def test_payment_router_handle_payment_webhook(self):
        """Test case for payment_router_handle_payment_webhook

        """
        pass


if __name__ == '__main__':
    unittest.main()
