# coding: utf-8

"""
    SendPost API

    SendPost API to send transactional emails reliably  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@sendx.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ModelsCleanedList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'detailed_response': 'list[ModelsSingleCleanedMail]',
        'invalid': 'object',
        'valid': 'object'
    }

    attribute_map = {
        'detailed_response': 'detailedResponse',
        'invalid': 'invalid',
        'valid': 'valid'
    }

    def __init__(self, detailed_response=None, invalid=None, valid=None):  # noqa: E501
        """ModelsCleanedList - a model defined in Swagger"""  # noqa: E501

        self._detailed_response = None
        self._invalid = None
        self._valid = None
        self.discriminator = None

        if detailed_response is not None:
            self.detailed_response = detailed_response
        if invalid is not None:
            self.invalid = invalid
        if valid is not None:
            self.valid = valid

    @property
    def detailed_response(self):
        """Gets the detailed_response of this ModelsCleanedList.  # noqa: E501


        :return: The detailed_response of this ModelsCleanedList.  # noqa: E501
        :rtype: list[ModelsSingleCleanedMail]
        """
        return self._detailed_response

    @detailed_response.setter
    def detailed_response(self, detailed_response):
        """Sets the detailed_response of this ModelsCleanedList.


        :param detailed_response: The detailed_response of this ModelsCleanedList.  # noqa: E501
        :type: list[ModelsSingleCleanedMail]
        """

        self._detailed_response = detailed_response

    @property
    def invalid(self):
        """Gets the invalid of this ModelsCleanedList.  # noqa: E501


        :return: The invalid of this ModelsCleanedList.  # noqa: E501
        :rtype: object
        """
        return self._invalid

    @invalid.setter
    def invalid(self, invalid):
        """Sets the invalid of this ModelsCleanedList.


        :param invalid: The invalid of this ModelsCleanedList.  # noqa: E501
        :type: object
        """

        self._invalid = invalid

    @property
    def valid(self):
        """Gets the valid of this ModelsCleanedList.  # noqa: E501


        :return: The valid of this ModelsCleanedList.  # noqa: E501
        :rtype: object
        """
        return self._valid

    @valid.setter
    def valid(self, valid):
        """Sets the valid of this ModelsCleanedList.


        :param valid: The valid of this ModelsCleanedList.  # noqa: E501
        :type: object
        """

        self._valid = valid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModelsCleanedList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelsCleanedList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
