# coding: utf-8

"""
    SendPost API

    SendPost API to send transactional emails reliably  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@sendx.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ModelsEmailResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error_code': 'ModelsEmailErrorCode',
        'message': 'str',
        'message_id': 'str',
        'submitted_at': 'int',
        'to': 'str'
    }

    attribute_map = {
        'error_code': 'errorCode',
        'message': 'message',
        'message_id': 'messageId',
        'submitted_at': 'submittedAt',
        'to': 'to'
    }

    def __init__(self, error_code=None, message=None, message_id=None, submitted_at=None, to=None):  # noqa: E501
        """ModelsEmailResponse - a model defined in Swagger"""  # noqa: E501

        self._error_code = None
        self._message = None
        self._message_id = None
        self._submitted_at = None
        self._to = None
        self.discriminator = None

        if error_code is not None:
            self.error_code = error_code
        if message is not None:
            self.message = message
        if message_id is not None:
            self.message_id = message_id
        if submitted_at is not None:
            self.submitted_at = submitted_at
        if to is not None:
            self.to = to

    @property
    def error_code(self):
        """Gets the error_code of this ModelsEmailResponse.  # noqa: E501


        :return: The error_code of this ModelsEmailResponse.  # noqa: E501
        :rtype: ModelsEmailErrorCode
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this ModelsEmailResponse.


        :param error_code: The error_code of this ModelsEmailResponse.  # noqa: E501
        :type: ModelsEmailErrorCode
        """

        self._error_code = error_code

    @property
    def message(self):
        """Gets the message of this ModelsEmailResponse.  # noqa: E501


        :return: The message of this ModelsEmailResponse.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ModelsEmailResponse.


        :param message: The message of this ModelsEmailResponse.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def message_id(self):
        """Gets the message_id of this ModelsEmailResponse.  # noqa: E501


        :return: The message_id of this ModelsEmailResponse.  # noqa: E501
        :rtype: str
        """
        return self._message_id

    @message_id.setter
    def message_id(self, message_id):
        """Sets the message_id of this ModelsEmailResponse.


        :param message_id: The message_id of this ModelsEmailResponse.  # noqa: E501
        :type: str
        """

        self._message_id = message_id

    @property
    def submitted_at(self):
        """Gets the submitted_at of this ModelsEmailResponse.  # noqa: E501


        :return: The submitted_at of this ModelsEmailResponse.  # noqa: E501
        :rtype: int
        """
        return self._submitted_at

    @submitted_at.setter
    def submitted_at(self, submitted_at):
        """Sets the submitted_at of this ModelsEmailResponse.


        :param submitted_at: The submitted_at of this ModelsEmailResponse.  # noqa: E501
        :type: int
        """

        self._submitted_at = submitted_at

    @property
    def to(self):
        """Gets the to of this ModelsEmailResponse.  # noqa: E501


        :return: The to of this ModelsEmailResponse.  # noqa: E501
        :rtype: str
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this ModelsEmailResponse.


        :param to: The to of this ModelsEmailResponse.  # noqa: E501
        :type: str
        """

        self._to = to

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModelsEmailResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelsEmailResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
