# coding: utf-8

"""
    SendPost API

    SendPost API to send transactional emails reliably  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@sendx.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ModelsDetailedAlert(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'active': 'bool',
        'entity_type': 'str',
        'entity_value': 'str',
        'id': 'int',
        'label': 'ModelsAlertLabel',
        'name': 'str',
        'parameter': 'int',
        'provider': 'str',
        'threshold': 'str'
    }

    attribute_map = {
        'active': 'active',
        'entity_type': 'entityType',
        'entity_value': 'entityValue',
        'id': 'id',
        'label': 'label',
        'name': 'name',
        'parameter': 'parameter',
        'provider': 'provider',
        'threshold': 'threshold'
    }

    def __init__(self, active=None, entity_type=None, entity_value=None, id=None, label=None, name=None, parameter=None, provider=None, threshold=None):  # noqa: E501
        """ModelsDetailedAlert - a model defined in Swagger"""  # noqa: E501

        self._active = None
        self._entity_type = None
        self._entity_value = None
        self._id = None
        self._label = None
        self._name = None
        self._parameter = None
        self._provider = None
        self._threshold = None
        self.discriminator = None

        if active is not None:
            self.active = active
        if entity_type is not None:
            self.entity_type = entity_type
        if entity_value is not None:
            self.entity_value = entity_value
        if id is not None:
            self.id = id
        if label is not None:
            self.label = label
        if name is not None:
            self.name = name
        if parameter is not None:
            self.parameter = parameter
        if provider is not None:
            self.provider = provider
        if threshold is not None:
            self.threshold = threshold

    @property
    def active(self):
        """Gets the active of this ModelsDetailedAlert.  # noqa: E501


        :return: The active of this ModelsDetailedAlert.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this ModelsDetailedAlert.


        :param active: The active of this ModelsDetailedAlert.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def entity_type(self):
        """Gets the entity_type of this ModelsDetailedAlert.  # noqa: E501


        :return: The entity_type of this ModelsDetailedAlert.  # noqa: E501
        :rtype: str
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type):
        """Sets the entity_type of this ModelsDetailedAlert.


        :param entity_type: The entity_type of this ModelsDetailedAlert.  # noqa: E501
        :type: str
        """

        self._entity_type = entity_type

    @property
    def entity_value(self):
        """Gets the entity_value of this ModelsDetailedAlert.  # noqa: E501


        :return: The entity_value of this ModelsDetailedAlert.  # noqa: E501
        :rtype: str
        """
        return self._entity_value

    @entity_value.setter
    def entity_value(self, entity_value):
        """Sets the entity_value of this ModelsDetailedAlert.


        :param entity_value: The entity_value of this ModelsDetailedAlert.  # noqa: E501
        :type: str
        """

        self._entity_value = entity_value

    @property
    def id(self):
        """Gets the id of this ModelsDetailedAlert.  # noqa: E501


        :return: The id of this ModelsDetailedAlert.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ModelsDetailedAlert.


        :param id: The id of this ModelsDetailedAlert.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def label(self):
        """Gets the label of this ModelsDetailedAlert.  # noqa: E501


        :return: The label of this ModelsDetailedAlert.  # noqa: E501
        :rtype: ModelsAlertLabel
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this ModelsDetailedAlert.


        :param label: The label of this ModelsDetailedAlert.  # noqa: E501
        :type: ModelsAlertLabel
        """

        self._label = label

    @property
    def name(self):
        """Gets the name of this ModelsDetailedAlert.  # noqa: E501


        :return: The name of this ModelsDetailedAlert.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ModelsDetailedAlert.


        :param name: The name of this ModelsDetailedAlert.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def parameter(self):
        """Gets the parameter of this ModelsDetailedAlert.  # noqa: E501


        :return: The parameter of this ModelsDetailedAlert.  # noqa: E501
        :rtype: int
        """
        return self._parameter

    @parameter.setter
    def parameter(self, parameter):
        """Sets the parameter of this ModelsDetailedAlert.


        :param parameter: The parameter of this ModelsDetailedAlert.  # noqa: E501
        :type: int
        """

        self._parameter = parameter

    @property
    def provider(self):
        """Gets the provider of this ModelsDetailedAlert.  # noqa: E501


        :return: The provider of this ModelsDetailedAlert.  # noqa: E501
        :rtype: str
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this ModelsDetailedAlert.


        :param provider: The provider of this ModelsDetailedAlert.  # noqa: E501
        :type: str
        """

        self._provider = provider

    @property
    def threshold(self):
        """Gets the threshold of this ModelsDetailedAlert.  # noqa: E501


        :return: The threshold of this ModelsDetailedAlert.  # noqa: E501
        :rtype: str
        """
        return self._threshold

    @threshold.setter
    def threshold(self, threshold):
        """Sets the threshold of this ModelsDetailedAlert.


        :param threshold: The threshold of this ModelsDetailedAlert.  # noqa: E501
        :type: str
        """

        self._threshold = threshold

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModelsDetailedAlert, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelsDetailedAlert):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
