# coding: utf-8

"""
    SendPost API

    SendPost API to send transactional emails reliably  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@sendx.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ModelsSingleCleanedMail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'email': 'str',
        'error': 'str',
        'reason': 'ModelsValidationReason',
        'valid': 'bool'
    }

    attribute_map = {
        'email': 'email',
        'error': 'error',
        'reason': 'reason',
        'valid': 'valid'
    }

    def __init__(self, email=None, error=None, reason=None, valid=None):  # noqa: E501
        """ModelsSingleCleanedMail - a model defined in Swagger"""  # noqa: E501

        self._email = None
        self._error = None
        self._reason = None
        self._valid = None
        self.discriminator = None

        if email is not None:
            self.email = email
        if error is not None:
            self.error = error
        if reason is not None:
            self.reason = reason
        if valid is not None:
            self.valid = valid

    @property
    def email(self):
        """Gets the email of this ModelsSingleCleanedMail.  # noqa: E501


        :return: The email of this ModelsSingleCleanedMail.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this ModelsSingleCleanedMail.


        :param email: The email of this ModelsSingleCleanedMail.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def error(self):
        """Gets the error of this ModelsSingleCleanedMail.  # noqa: E501


        :return: The error of this ModelsSingleCleanedMail.  # noqa: E501
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this ModelsSingleCleanedMail.


        :param error: The error of this ModelsSingleCleanedMail.  # noqa: E501
        :type: str
        """

        self._error = error

    @property
    def reason(self):
        """Gets the reason of this ModelsSingleCleanedMail.  # noqa: E501


        :return: The reason of this ModelsSingleCleanedMail.  # noqa: E501
        :rtype: ModelsValidationReason
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this ModelsSingleCleanedMail.


        :param reason: The reason of this ModelsSingleCleanedMail.  # noqa: E501
        :type: ModelsValidationReason
        """

        self._reason = reason

    @property
    def valid(self):
        """Gets the valid of this ModelsSingleCleanedMail.  # noqa: E501


        :return: The valid of this ModelsSingleCleanedMail.  # noqa: E501
        :rtype: bool
        """
        return self._valid

    @valid.setter
    def valid(self, valid):
        """Sets the valid of this ModelsSingleCleanedMail.


        :param valid: The valid of this ModelsSingleCleanedMail.  # noqa: E501
        :type: bool
        """

        self._valid = valid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModelsSingleCleanedMail, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelsSingleCleanedMail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
