# coding: utf-8

"""
    SendPost API

    SendPost API to send transactional emails reliably  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@sendx.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ModelsSMTPAuth(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created': 'int',
        'id': 'int',
        'password': 'str',
        'updated': 'int',
        'username': 'str'
    }

    attribute_map = {
        'created': 'created',
        'id': 'id',
        'password': 'password',
        'updated': 'updated',
        'username': 'username'
    }

    def __init__(self, created=None, id=None, password=None, updated=None, username=None):  # noqa: E501
        """ModelsSMTPAuth - a model defined in Swagger"""  # noqa: E501

        self._created = None
        self._id = None
        self._password = None
        self._updated = None
        self._username = None
        self.discriminator = None

        if created is not None:
            self.created = created
        if id is not None:
            self.id = id
        if password is not None:
            self.password = password
        if updated is not None:
            self.updated = updated
        if username is not None:
            self.username = username

    @property
    def created(self):
        """Gets the created of this ModelsSMTPAuth.  # noqa: E501


        :return: The created of this ModelsSMTPAuth.  # noqa: E501
        :rtype: int
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this ModelsSMTPAuth.


        :param created: The created of this ModelsSMTPAuth.  # noqa: E501
        :type: int
        """

        self._created = created

    @property
    def id(self):
        """Gets the id of this ModelsSMTPAuth.  # noqa: E501


        :return: The id of this ModelsSMTPAuth.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ModelsSMTPAuth.


        :param id: The id of this ModelsSMTPAuth.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def password(self):
        """Gets the password of this ModelsSMTPAuth.  # noqa: E501


        :return: The password of this ModelsSMTPAuth.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this ModelsSMTPAuth.


        :param password: The password of this ModelsSMTPAuth.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def updated(self):
        """Gets the updated of this ModelsSMTPAuth.  # noqa: E501


        :return: The updated of this ModelsSMTPAuth.  # noqa: E501
        :rtype: int
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this ModelsSMTPAuth.


        :param updated: The updated of this ModelsSMTPAuth.  # noqa: E501
        :type: int
        """

        self._updated = updated

    @property
    def username(self):
        """Gets the username of this ModelsSMTPAuth.  # noqa: E501


        :return: The username of this ModelsSMTPAuth.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this ModelsSMTPAuth.


        :param username: The username of this ModelsSMTPAuth.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModelsSMTPAuth, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelsSMTPAuth):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
