# coding: utf-8

"""
    SendPost API

    SendPost API to send transactional emails reliably  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@sendx.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class AccountstatApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def account_stat_router_get_all_account_stats(self, x_account_api_key, **kwargs):  # noqa: E501
        """account_stat_router_get_all_account_stats  # noqa: E501

        Get All Account Stats  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.account_stat_router_get_all_account_stats(x_account_api_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Sub-Account API Key (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsRStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.account_stat_router_get_all_account_stats_with_http_info(x_account_api_key, **kwargs)  # noqa: E501
        else:
            (data) = self.account_stat_router_get_all_account_stats_with_http_info(x_account_api_key, **kwargs)  # noqa: E501
            return data

    def account_stat_router_get_all_account_stats_with_http_info(self, x_account_api_key, **kwargs):  # noqa: E501
        """account_stat_router_get_all_account_stats  # noqa: E501

        Get All Account Stats  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.account_stat_router_get_all_account_stats_with_http_info(x_account_api_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Sub-Account API Key (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsRStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_account_api_key', '_from', 'to']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method account_stat_router_get_all_account_stats" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_account_api_key' is set
        if ('x_account_api_key' not in params or
                params['x_account_api_key'] is None):
            raise ValueError("Missing the required parameter `x_account_api_key` when calling `account_stat_router_get_all_account_stats`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'to' in params:
            query_params.append(('to', params['to']))  # noqa: E501

        header_params = {}
        if 'x_account_api_key' in params:
            header_params['X-Account-ApiKey'] = params['x_account_api_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/account/stat/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ModelsRStat]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def account_stat_router_get_all_account_stats_by_group(self, x_account_api_key, group, **kwargs):  # noqa: E501
        """account_stat_router_get_all_account_stats_by_group  # noqa: E501

        Get All Account Stats by Group  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.account_stat_router_get_all_account_stats_by_group(x_account_api_key, group, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Sub-Account API Key (required)
        :param str group: the group whose stats you want (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsRStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.account_stat_router_get_all_account_stats_by_group_with_http_info(x_account_api_key, group, **kwargs)  # noqa: E501
        else:
            (data) = self.account_stat_router_get_all_account_stats_by_group_with_http_info(x_account_api_key, group, **kwargs)  # noqa: E501
            return data

    def account_stat_router_get_all_account_stats_by_group_with_http_info(self, x_account_api_key, group, **kwargs):  # noqa: E501
        """account_stat_router_get_all_account_stats_by_group  # noqa: E501

        Get All Account Stats by Group  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.account_stat_router_get_all_account_stats_by_group_with_http_info(x_account_api_key, group, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Sub-Account API Key (required)
        :param str group: the group whose stats you want (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsRStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_account_api_key', 'group', '_from', 'to']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method account_stat_router_get_all_account_stats_by_group" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_account_api_key' is set
        if ('x_account_api_key' not in params or
                params['x_account_api_key'] is None):
            raise ValueError("Missing the required parameter `x_account_api_key` when calling `account_stat_router_get_all_account_stats_by_group`")  # noqa: E501
        # verify the required parameter 'group' is set
        if ('group' not in params or
                params['group'] is None):
            raise ValueError("Missing the required parameter `group` when calling `account_stat_router_get_all_account_stats_by_group`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'to' in params:
            query_params.append(('to', params['to']))  # noqa: E501
        if 'group' in params:
            query_params.append(('group', params['group']))  # noqa: E501

        header_params = {}
        if 'x_account_api_key' in params:
            header_params['X-Account-ApiKey'] = params['x_account_api_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/account/stat/group', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ModelsRStat]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def account_stat_router_get_all_aggregate_account_stats(self, x_account_api_key, **kwargs):  # noqa: E501
        """account_stat_router_get_all_aggregate_account_stats  # noqa: E501

        Get All Aggregate Stats  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.account_stat_router_get_all_aggregate_account_stats(x_account_api_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Sub-Account API Key (required)
        :param str _from: from date
        :param str to: to date
        :return: ModelsStat
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.account_stat_router_get_all_aggregate_account_stats_with_http_info(x_account_api_key, **kwargs)  # noqa: E501
        else:
            (data) = self.account_stat_router_get_all_aggregate_account_stats_with_http_info(x_account_api_key, **kwargs)  # noqa: E501
            return data

    def account_stat_router_get_all_aggregate_account_stats_with_http_info(self, x_account_api_key, **kwargs):  # noqa: E501
        """account_stat_router_get_all_aggregate_account_stats  # noqa: E501

        Get All Aggregate Stats  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.account_stat_router_get_all_aggregate_account_stats_with_http_info(x_account_api_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Sub-Account API Key (required)
        :param str _from: from date
        :param str to: to date
        :return: ModelsStat
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_account_api_key', '_from', 'to']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method account_stat_router_get_all_aggregate_account_stats" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_account_api_key' is set
        if ('x_account_api_key' not in params or
                params['x_account_api_key'] is None):
            raise ValueError("Missing the required parameter `x_account_api_key` when calling `account_stat_router_get_all_aggregate_account_stats`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'to' in params:
            query_params.append(('to', params['to']))  # noqa: E501

        header_params = {}
        if 'x_account_api_key' in params:
            header_params['X-Account-ApiKey'] = params['x_account_api_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/account/stat/aggregate', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ModelsStat',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def account_stat_router_get_all_aggregate_account_stats_by_group(self, x_account_api_key, group, **kwargs):  # noqa: E501
        """account_stat_router_get_all_aggregate_account_stats_by_group  # noqa: E501

        Get All Aggregate Stats by Group  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.account_stat_router_get_all_aggregate_account_stats_by_group(x_account_api_key, group, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Sub-Account API Key (required)
        :param str group: the group whose stats you want (required)
        :param str _from: from date
        :param str to: to date
        :return: ModelsStat
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.account_stat_router_get_all_aggregate_account_stats_by_group_with_http_info(x_account_api_key, group, **kwargs)  # noqa: E501
        else:
            (data) = self.account_stat_router_get_all_aggregate_account_stats_by_group_with_http_info(x_account_api_key, group, **kwargs)  # noqa: E501
            return data

    def account_stat_router_get_all_aggregate_account_stats_by_group_with_http_info(self, x_account_api_key, group, **kwargs):  # noqa: E501
        """account_stat_router_get_all_aggregate_account_stats_by_group  # noqa: E501

        Get All Aggregate Stats by Group  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.account_stat_router_get_all_aggregate_account_stats_by_group_with_http_info(x_account_api_key, group, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Sub-Account API Key (required)
        :param str group: the group whose stats you want (required)
        :param str _from: from date
        :param str to: to date
        :return: ModelsStat
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_account_api_key', 'group', '_from', 'to']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method account_stat_router_get_all_aggregate_account_stats_by_group" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_account_api_key' is set
        if ('x_account_api_key' not in params or
                params['x_account_api_key'] is None):
            raise ValueError("Missing the required parameter `x_account_api_key` when calling `account_stat_router_get_all_aggregate_account_stats_by_group`")  # noqa: E501
        # verify the required parameter 'group' is set
        if ('group' not in params or
                params['group'] is None):
            raise ValueError("Missing the required parameter `group` when calling `account_stat_router_get_all_aggregate_account_stats_by_group`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'to' in params:
            query_params.append(('to', params['to']))  # noqa: E501
        if 'group' in params:
            query_params.append(('group', params['group']))  # noqa: E501

        header_params = {}
        if 'x_account_api_key' in params:
            header_params['X-Account-ApiKey'] = params['x_account_api_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/account/stat/aggregate/group', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ModelsStat',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
