# coding: utf-8

"""
    SendPost API

    SendPost API to send transactional emails reliably  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@sendx.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class AccountipstatApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def i_p_stat_router_get_all_aggregate_ip_stats(self, x_account_api_key, ipid, **kwargs):  # noqa: E501
        """i_p_stat_router_get_all_aggregate_ip_stats  # noqa: E501

        Get All Aggregate Stats  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_p_stat_router_get_all_aggregate_ip_stats(x_account_api_key, ipid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Account API Key (required)
        :param int ipid: the IPId you want to get (required)
        :param str _from: from date
        :param str to: to date
        :return: ModelsStat
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_p_stat_router_get_all_aggregate_ip_stats_with_http_info(x_account_api_key, ipid, **kwargs)  # noqa: E501
        else:
            (data) = self.i_p_stat_router_get_all_aggregate_ip_stats_with_http_info(x_account_api_key, ipid, **kwargs)  # noqa: E501
            return data

    def i_p_stat_router_get_all_aggregate_ip_stats_with_http_info(self, x_account_api_key, ipid, **kwargs):  # noqa: E501
        """i_p_stat_router_get_all_aggregate_ip_stats  # noqa: E501

        Get All Aggregate Stats  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_p_stat_router_get_all_aggregate_ip_stats_with_http_info(x_account_api_key, ipid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Account API Key (required)
        :param int ipid: the IPId you want to get (required)
        :param str _from: from date
        :param str to: to date
        :return: ModelsStat
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_account_api_key', 'ipid', '_from', 'to']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_p_stat_router_get_all_aggregate_ip_stats" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_account_api_key' is set
        if ('x_account_api_key' not in params or
                params['x_account_api_key'] is None):
            raise ValueError("Missing the required parameter `x_account_api_key` when calling `i_p_stat_router_get_all_aggregate_ip_stats`")  # noqa: E501
        # verify the required parameter 'ipid' is set
        if ('ipid' not in params or
                params['ipid'] is None):
            raise ValueError("Missing the required parameter `ipid` when calling `i_p_stat_router_get_all_aggregate_ip_stats`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ipid' in params:
            path_params['ipid'] = params['ipid']  # noqa: E501

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'to' in params:
            query_params.append(('to', params['to']))  # noqa: E501

        header_params = {}
        if 'x_account_api_key' in params:
            header_params['X-Account-ApiKey'] = params['x_account_api_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/account/ip/stat/{ipid}/aggregate', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ModelsStat',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_p_stat_router_get_all_aggregate_ip_stats_by_group(self, x_account_api_key, ipid, provider, **kwargs):  # noqa: E501
        """i_p_stat_router_get_all_aggregate_ip_stats_by_group  # noqa: E501

        Get All Aggregate Stats by Group  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_p_stat_router_get_all_aggregate_ip_stats_by_group(x_account_api_key, ipid, provider, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Account API Key (required)
        :param int ipid: the IPId you want to get (required)
        :param str provider: the group whose stats you want (required)
        :param str _from: from date
        :param str to: to date
        :return: ModelsStat
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_p_stat_router_get_all_aggregate_ip_stats_by_group_with_http_info(x_account_api_key, ipid, provider, **kwargs)  # noqa: E501
        else:
            (data) = self.i_p_stat_router_get_all_aggregate_ip_stats_by_group_with_http_info(x_account_api_key, ipid, provider, **kwargs)  # noqa: E501
            return data

    def i_p_stat_router_get_all_aggregate_ip_stats_by_group_with_http_info(self, x_account_api_key, ipid, provider, **kwargs):  # noqa: E501
        """i_p_stat_router_get_all_aggregate_ip_stats_by_group  # noqa: E501

        Get All Aggregate Stats by Group  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_p_stat_router_get_all_aggregate_ip_stats_by_group_with_http_info(x_account_api_key, ipid, provider, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Account API Key (required)
        :param int ipid: the IPId you want to get (required)
        :param str provider: the group whose stats you want (required)
        :param str _from: from date
        :param str to: to date
        :return: ModelsStat
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_account_api_key', 'ipid', 'provider', '_from', 'to']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_p_stat_router_get_all_aggregate_ip_stats_by_group" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_account_api_key' is set
        if ('x_account_api_key' not in params or
                params['x_account_api_key'] is None):
            raise ValueError("Missing the required parameter `x_account_api_key` when calling `i_p_stat_router_get_all_aggregate_ip_stats_by_group`")  # noqa: E501
        # verify the required parameter 'ipid' is set
        if ('ipid' not in params or
                params['ipid'] is None):
            raise ValueError("Missing the required parameter `ipid` when calling `i_p_stat_router_get_all_aggregate_ip_stats_by_group`")  # noqa: E501
        # verify the required parameter 'provider' is set
        if ('provider' not in params or
                params['provider'] is None):
            raise ValueError("Missing the required parameter `provider` when calling `i_p_stat_router_get_all_aggregate_ip_stats_by_group`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ipid' in params:
            path_params['ipid'] = params['ipid']  # noqa: E501

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'to' in params:
            query_params.append(('to', params['to']))  # noqa: E501
        if 'provider' in params:
            query_params.append(('provider', params['provider']))  # noqa: E501

        header_params = {}
        if 'x_account_api_key' in params:
            header_params['X-Account-ApiKey'] = params['x_account_api_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/account/ip/stat/{ipid}/aggregate/provider', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ModelsStat',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_p_stat_router_get_all_aggregated_provider_stats_for_a_ip(self, x_account_api_key, ipid, **kwargs):  # noqa: E501
        """i_p_stat_router_get_all_aggregated_provider_stats_for_a_ip  # noqa: E501

        Get All Aggregated Provider Stats for a IP  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_p_stat_router_get_all_aggregated_provider_stats_for_a_ip(x_account_api_key, ipid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Account API Key (required)
        :param int ipid: the IPId you want to get (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsPIPStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_p_stat_router_get_all_aggregated_provider_stats_for_a_ip_with_http_info(x_account_api_key, ipid, **kwargs)  # noqa: E501
        else:
            (data) = self.i_p_stat_router_get_all_aggregated_provider_stats_for_a_ip_with_http_info(x_account_api_key, ipid, **kwargs)  # noqa: E501
            return data

    def i_p_stat_router_get_all_aggregated_provider_stats_for_a_ip_with_http_info(self, x_account_api_key, ipid, **kwargs):  # noqa: E501
        """i_p_stat_router_get_all_aggregated_provider_stats_for_a_ip  # noqa: E501

        Get All Aggregated Provider Stats for a IP  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_p_stat_router_get_all_aggregated_provider_stats_for_a_ip_with_http_info(x_account_api_key, ipid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Account API Key (required)
        :param int ipid: the IPId you want to get (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsPIPStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_account_api_key', 'ipid', '_from', 'to']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_p_stat_router_get_all_aggregated_provider_stats_for_a_ip" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_account_api_key' is set
        if ('x_account_api_key' not in params or
                params['x_account_api_key'] is None):
            raise ValueError("Missing the required parameter `x_account_api_key` when calling `i_p_stat_router_get_all_aggregated_provider_stats_for_a_ip`")  # noqa: E501
        # verify the required parameter 'ipid' is set
        if ('ipid' not in params or
                params['ipid'] is None):
            raise ValueError("Missing the required parameter `ipid` when calling `i_p_stat_router_get_all_aggregated_provider_stats_for_a_ip`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ipid' in params:
            path_params['ipid'] = params['ipid']  # noqa: E501

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'to' in params:
            query_params.append(('to', params['to']))  # noqa: E501

        header_params = {}
        if 'x_account_api_key' in params:
            header_params['X-Account-ApiKey'] = params['x_account_api_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/account/ip/stat/{ipid}/aggregate/providers', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ModelsPIPStat]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_p_stat_router_get_all_aggregated_provider_stats_for_a_specific_sub_account_of_a_ip(self, x_account_api_key, ipid, sid, **kwargs):  # noqa: E501
        """i_p_stat_router_get_all_aggregated_provider_stats_for_a_specific_sub_account_of_a_ip  # noqa: E501

        Get All Aggregated Provider Stats for a Specific Sub-Account of a IP  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_p_stat_router_get_all_aggregated_provider_stats_for_a_specific_sub_account_of_a_ip(x_account_api_key, ipid, sid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Account API Key (required)
        :param int ipid: the IPId you want to get (required)
        :param int sid: the Sub Account Id you want to get (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsPIPStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_p_stat_router_get_all_aggregated_provider_stats_for_a_specific_sub_account_of_a_ip_with_http_info(x_account_api_key, ipid, sid, **kwargs)  # noqa: E501
        else:
            (data) = self.i_p_stat_router_get_all_aggregated_provider_stats_for_a_specific_sub_account_of_a_ip_with_http_info(x_account_api_key, ipid, sid, **kwargs)  # noqa: E501
            return data

    def i_p_stat_router_get_all_aggregated_provider_stats_for_a_specific_sub_account_of_a_ip_with_http_info(self, x_account_api_key, ipid, sid, **kwargs):  # noqa: E501
        """i_p_stat_router_get_all_aggregated_provider_stats_for_a_specific_sub_account_of_a_ip  # noqa: E501

        Get All Aggregated Provider Stats for a Specific Sub-Account of a IP  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_p_stat_router_get_all_aggregated_provider_stats_for_a_specific_sub_account_of_a_ip_with_http_info(x_account_api_key, ipid, sid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Account API Key (required)
        :param int ipid: the IPId you want to get (required)
        :param int sid: the Sub Account Id you want to get (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsPIPStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_account_api_key', 'ipid', 'sid', '_from', 'to']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_p_stat_router_get_all_aggregated_provider_stats_for_a_specific_sub_account_of_a_ip" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_account_api_key' is set
        if ('x_account_api_key' not in params or
                params['x_account_api_key'] is None):
            raise ValueError("Missing the required parameter `x_account_api_key` when calling `i_p_stat_router_get_all_aggregated_provider_stats_for_a_specific_sub_account_of_a_ip`")  # noqa: E501
        # verify the required parameter 'ipid' is set
        if ('ipid' not in params or
                params['ipid'] is None):
            raise ValueError("Missing the required parameter `ipid` when calling `i_p_stat_router_get_all_aggregated_provider_stats_for_a_specific_sub_account_of_a_ip`")  # noqa: E501
        # verify the required parameter 'sid' is set
        if ('sid' not in params or
                params['sid'] is None):
            raise ValueError("Missing the required parameter `sid` when calling `i_p_stat_router_get_all_aggregated_provider_stats_for_a_specific_sub_account_of_a_ip`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ipid' in params:
            path_params['ipid'] = params['ipid']  # noqa: E501
        if 'sid' in params:
            path_params['sid'] = params['sid']  # noqa: E501

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'to' in params:
            query_params.append(('to', params['to']))  # noqa: E501

        header_params = {}
        if 'x_account_api_key' in params:
            header_params['X-Account-ApiKey'] = params['x_account_api_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/account/ip/stat/{ipid}/aggregate/sid/{sid}/providers', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ModelsPIPStat]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_p_stat_router_get_all_aggregated_sub_account_stats_for_an_ip(self, x_account_api_key, ipid, **kwargs):  # noqa: E501
        """i_p_stat_router_get_all_aggregated_sub_account_stats_for_an_ip  # noqa: E501

        Get All Aggregated Sub-Account Stats for an IP  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_p_stat_router_get_all_aggregated_sub_account_stats_for_an_ip(x_account_api_key, ipid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Account API Key (required)
        :param int ipid: the IPId you want to get (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsSIPStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_p_stat_router_get_all_aggregated_sub_account_stats_for_an_ip_with_http_info(x_account_api_key, ipid, **kwargs)  # noqa: E501
        else:
            (data) = self.i_p_stat_router_get_all_aggregated_sub_account_stats_for_an_ip_with_http_info(x_account_api_key, ipid, **kwargs)  # noqa: E501
            return data

    def i_p_stat_router_get_all_aggregated_sub_account_stats_for_an_ip_with_http_info(self, x_account_api_key, ipid, **kwargs):  # noqa: E501
        """i_p_stat_router_get_all_aggregated_sub_account_stats_for_an_ip  # noqa: E501

        Get All Aggregated Sub-Account Stats for an IP  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_p_stat_router_get_all_aggregated_sub_account_stats_for_an_ip_with_http_info(x_account_api_key, ipid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Account API Key (required)
        :param int ipid: the IPId you want to get (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsSIPStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_account_api_key', 'ipid', '_from', 'to']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_p_stat_router_get_all_aggregated_sub_account_stats_for_an_ip" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_account_api_key' is set
        if ('x_account_api_key' not in params or
                params['x_account_api_key'] is None):
            raise ValueError("Missing the required parameter `x_account_api_key` when calling `i_p_stat_router_get_all_aggregated_sub_account_stats_for_an_ip`")  # noqa: E501
        # verify the required parameter 'ipid' is set
        if ('ipid' not in params or
                params['ipid'] is None):
            raise ValueError("Missing the required parameter `ipid` when calling `i_p_stat_router_get_all_aggregated_sub_account_stats_for_an_ip`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ipid' in params:
            path_params['ipid'] = params['ipid']  # noqa: E501

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'to' in params:
            query_params.append(('to', params['to']))  # noqa: E501

        header_params = {}
        if 'x_account_api_key' in params:
            header_params['X-Account-ApiKey'] = params['x_account_api_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/account/ip/stat/{ipid}/aggregate/subaccounts', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ModelsSIPStat]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_p_stat_router_get_all_ip_stats(self, x_account_api_key, ipid, **kwargs):  # noqa: E501
        """i_p_stat_router_get_all_ip_stats  # noqa: E501

        Get All IP Stats  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_p_stat_router_get_all_ip_stats(x_account_api_key, ipid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Account API Key (required)
        :param int ipid: the IPId you want to get (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsRIPStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_p_stat_router_get_all_ip_stats_with_http_info(x_account_api_key, ipid, **kwargs)  # noqa: E501
        else:
            (data) = self.i_p_stat_router_get_all_ip_stats_with_http_info(x_account_api_key, ipid, **kwargs)  # noqa: E501
            return data

    def i_p_stat_router_get_all_ip_stats_with_http_info(self, x_account_api_key, ipid, **kwargs):  # noqa: E501
        """i_p_stat_router_get_all_ip_stats  # noqa: E501

        Get All IP Stats  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_p_stat_router_get_all_ip_stats_with_http_info(x_account_api_key, ipid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_account_api_key: Account API Key (required)
        :param int ipid: the IPId you want to get (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsRIPStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_account_api_key', 'ipid', '_from', 'to']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_p_stat_router_get_all_ip_stats" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_account_api_key' is set
        if ('x_account_api_key' not in params or
                params['x_account_api_key'] is None):
            raise ValueError("Missing the required parameter `x_account_api_key` when calling `i_p_stat_router_get_all_ip_stats`")  # noqa: E501
        # verify the required parameter 'ipid' is set
        if ('ipid' not in params or
                params['ipid'] is None):
            raise ValueError("Missing the required parameter `ipid` when calling `i_p_stat_router_get_all_ip_stats`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ipid' in params:
            path_params['ipid'] = params['ipid']  # noqa: E501

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'to' in params:
            query_params.append(('to', params['to']))  # noqa: E501

        header_params = {}
        if 'x_account_api_key' in params:
            header_params['X-Account-ApiKey'] = params['x_account_api_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/account/ip/stat/{ipid}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ModelsRIPStat]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_p_stat_router_get_all_ip_stats_by_group(self, ipid, x_account_api_key, provider, **kwargs):  # noqa: E501
        """i_p_stat_router_get_all_ip_stats_by_group  # noqa: E501

        Get All IP Stats by Group  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_p_stat_router_get_all_ip_stats_by_group(ipid, x_account_api_key, provider, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int ipid: the IPId you want to get (required)
        :param str x_account_api_key: Account API Key (required)
        :param str provider: the provider whose stats you want (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsRIPStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_p_stat_router_get_all_ip_stats_by_group_with_http_info(ipid, x_account_api_key, provider, **kwargs)  # noqa: E501
        else:
            (data) = self.i_p_stat_router_get_all_ip_stats_by_group_with_http_info(ipid, x_account_api_key, provider, **kwargs)  # noqa: E501
            return data

    def i_p_stat_router_get_all_ip_stats_by_group_with_http_info(self, ipid, x_account_api_key, provider, **kwargs):  # noqa: E501
        """i_p_stat_router_get_all_ip_stats_by_group  # noqa: E501

        Get All IP Stats by Group  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_p_stat_router_get_all_ip_stats_by_group_with_http_info(ipid, x_account_api_key, provider, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int ipid: the IPId you want to get (required)
        :param str x_account_api_key: Account API Key (required)
        :param str provider: the provider whose stats you want (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsRIPStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ipid', 'x_account_api_key', 'provider', '_from', 'to']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_p_stat_router_get_all_ip_stats_by_group" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ipid' is set
        if ('ipid' not in params or
                params['ipid'] is None):
            raise ValueError("Missing the required parameter `ipid` when calling `i_p_stat_router_get_all_ip_stats_by_group`")  # noqa: E501
        # verify the required parameter 'x_account_api_key' is set
        if ('x_account_api_key' not in params or
                params['x_account_api_key'] is None):
            raise ValueError("Missing the required parameter `x_account_api_key` when calling `i_p_stat_router_get_all_ip_stats_by_group`")  # noqa: E501
        # verify the required parameter 'provider' is set
        if ('provider' not in params or
                params['provider'] is None):
            raise ValueError("Missing the required parameter `provider` when calling `i_p_stat_router_get_all_ip_stats_by_group`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ipid' in params:
            path_params['ipid'] = params['ipid']  # noqa: E501

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'to' in params:
            query_params.append(('to', params['to']))  # noqa: E501
        if 'provider' in params:
            query_params.append(('provider', params['provider']))  # noqa: E501

        header_params = {}
        if 'x_account_api_key' in params:
            header_params['X-Account-ApiKey'] = params['x_account_api_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/account/ip/stat/{ipid}/provider', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ModelsRIPStat]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
