# coding: utf-8

"""
    SendPost API

    SendPost API to send transactional emails reliably  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@sendx.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class SubaccountstatApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def sub_account_stat_router_get_all_aggregate_sub_account_stats(self, x_sub_account_api_key, **kwargs):  # noqa: E501
        """sub_account_stat_router_get_all_aggregate_sub_account_stats  # noqa: E501

        Get All Aggregate Sub-Account Stats  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.sub_account_stat_router_get_all_aggregate_sub_account_stats(x_sub_account_api_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_sub_account_api_key: Sub-Account API Key (required)
        :param str _from: from date
        :param str to: to date
        :return: ModelsStat
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.sub_account_stat_router_get_all_aggregate_sub_account_stats_with_http_info(x_sub_account_api_key, **kwargs)  # noqa: E501
        else:
            (data) = self.sub_account_stat_router_get_all_aggregate_sub_account_stats_with_http_info(x_sub_account_api_key, **kwargs)  # noqa: E501
            return data

    def sub_account_stat_router_get_all_aggregate_sub_account_stats_with_http_info(self, x_sub_account_api_key, **kwargs):  # noqa: E501
        """sub_account_stat_router_get_all_aggregate_sub_account_stats  # noqa: E501

        Get All Aggregate Sub-Account Stats  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.sub_account_stat_router_get_all_aggregate_sub_account_stats_with_http_info(x_sub_account_api_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_sub_account_api_key: Sub-Account API Key (required)
        :param str _from: from date
        :param str to: to date
        :return: ModelsStat
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_sub_account_api_key', '_from', 'to']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method sub_account_stat_router_get_all_aggregate_sub_account_stats" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_sub_account_api_key' is set
        if ('x_sub_account_api_key' not in params or
                params['x_sub_account_api_key'] is None):
            raise ValueError("Missing the required parameter `x_sub_account_api_key` when calling `sub_account_stat_router_get_all_aggregate_sub_account_stats`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'to' in params:
            query_params.append(('to', params['to']))  # noqa: E501

        header_params = {}
        if 'x_sub_account_api_key' in params:
            header_params['X-SubAccount-ApiKey'] = params['x_sub_account_api_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/subaccount/stat/aggregate', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ModelsStat',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def sub_account_stat_router_get_all_aggregate_sub_account_stats_by_group(self, x_sub_account_api_key, group, **kwargs):  # noqa: E501
        """sub_account_stat_router_get_all_aggregate_sub_account_stats_by_group  # noqa: E501

        Get All Aggregate Sub-Account Stats by Group  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.sub_account_stat_router_get_all_aggregate_sub_account_stats_by_group(x_sub_account_api_key, group, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_sub_account_api_key: Sub-Account API Key (required)
        :param str group: the group whose stats you want (required)
        :param str _from: from date
        :param str to: to date
        :return: ModelsStat
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.sub_account_stat_router_get_all_aggregate_sub_account_stats_by_group_with_http_info(x_sub_account_api_key, group, **kwargs)  # noqa: E501
        else:
            (data) = self.sub_account_stat_router_get_all_aggregate_sub_account_stats_by_group_with_http_info(x_sub_account_api_key, group, **kwargs)  # noqa: E501
            return data

    def sub_account_stat_router_get_all_aggregate_sub_account_stats_by_group_with_http_info(self, x_sub_account_api_key, group, **kwargs):  # noqa: E501
        """sub_account_stat_router_get_all_aggregate_sub_account_stats_by_group  # noqa: E501

        Get All Aggregate Sub-Account Stats by Group  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.sub_account_stat_router_get_all_aggregate_sub_account_stats_by_group_with_http_info(x_sub_account_api_key, group, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_sub_account_api_key: Sub-Account API Key (required)
        :param str group: the group whose stats you want (required)
        :param str _from: from date
        :param str to: to date
        :return: ModelsStat
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_sub_account_api_key', 'group', '_from', 'to']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method sub_account_stat_router_get_all_aggregate_sub_account_stats_by_group" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_sub_account_api_key' is set
        if ('x_sub_account_api_key' not in params or
                params['x_sub_account_api_key'] is None):
            raise ValueError("Missing the required parameter `x_sub_account_api_key` when calling `sub_account_stat_router_get_all_aggregate_sub_account_stats_by_group`")  # noqa: E501
        # verify the required parameter 'group' is set
        if ('group' not in params or
                params['group'] is None):
            raise ValueError("Missing the required parameter `group` when calling `sub_account_stat_router_get_all_aggregate_sub_account_stats_by_group`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'to' in params:
            query_params.append(('to', params['to']))  # noqa: E501
        if 'group' in params:
            query_params.append(('group', params['group']))  # noqa: E501

        header_params = {}
        if 'x_sub_account_api_key' in params:
            header_params['X-SubAccount-ApiKey'] = params['x_sub_account_api_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/subaccount/stat/aggregate/group', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ModelsStat',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def sub_account_stat_router_get_all_aggregated_group_stats_for_a_sub_account(self, x_sub_account_api_key, **kwargs):  # noqa: E501
        """sub_account_stat_router_get_all_aggregated_group_stats_for_a_sub_account  # noqa: E501

        Get All Aggregated Group Stats for a Sub-Account  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.sub_account_stat_router_get_all_aggregated_group_stats_for_a_sub_account(x_sub_account_api_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_sub_account_api_key: Sub-Account API Key (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsAGStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.sub_account_stat_router_get_all_aggregated_group_stats_for_a_sub_account_with_http_info(x_sub_account_api_key, **kwargs)  # noqa: E501
        else:
            (data) = self.sub_account_stat_router_get_all_aggregated_group_stats_for_a_sub_account_with_http_info(x_sub_account_api_key, **kwargs)  # noqa: E501
            return data

    def sub_account_stat_router_get_all_aggregated_group_stats_for_a_sub_account_with_http_info(self, x_sub_account_api_key, **kwargs):  # noqa: E501
        """sub_account_stat_router_get_all_aggregated_group_stats_for_a_sub_account  # noqa: E501

        Get All Aggregated Group Stats for a Sub-Account  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.sub_account_stat_router_get_all_aggregated_group_stats_for_a_sub_account_with_http_info(x_sub_account_api_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_sub_account_api_key: Sub-Account API Key (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsAGStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_sub_account_api_key', '_from', 'to']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method sub_account_stat_router_get_all_aggregated_group_stats_for_a_sub_account" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_sub_account_api_key' is set
        if ('x_sub_account_api_key' not in params or
                params['x_sub_account_api_key'] is None):
            raise ValueError("Missing the required parameter `x_sub_account_api_key` when calling `sub_account_stat_router_get_all_aggregated_group_stats_for_a_sub_account`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'to' in params:
            query_params.append(('to', params['to']))  # noqa: E501

        header_params = {}
        if 'x_sub_account_api_key' in params:
            header_params['X-SubAccount-ApiKey'] = params['x_sub_account_api_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/subaccount/stat/aggregate/groups', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ModelsAGStat]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def sub_account_stat_router_get_all_aggregated_ip_stats_for_a_sub_account(self, x_sub_account_api_key, **kwargs):  # noqa: E501
        """sub_account_stat_router_get_all_aggregated_ip_stats_for_a_sub_account  # noqa: E501

        Get All Aggregated IP Stats for a Sub-Account  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.sub_account_stat_router_get_all_aggregated_ip_stats_for_a_sub_account(x_sub_account_api_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_sub_account_api_key: Sub-Account API Key (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsAIPStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.sub_account_stat_router_get_all_aggregated_ip_stats_for_a_sub_account_with_http_info(x_sub_account_api_key, **kwargs)  # noqa: E501
        else:
            (data) = self.sub_account_stat_router_get_all_aggregated_ip_stats_for_a_sub_account_with_http_info(x_sub_account_api_key, **kwargs)  # noqa: E501
            return data

    def sub_account_stat_router_get_all_aggregated_ip_stats_for_a_sub_account_with_http_info(self, x_sub_account_api_key, **kwargs):  # noqa: E501
        """sub_account_stat_router_get_all_aggregated_ip_stats_for_a_sub_account  # noqa: E501

        Get All Aggregated IP Stats for a Sub-Account  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.sub_account_stat_router_get_all_aggregated_ip_stats_for_a_sub_account_with_http_info(x_sub_account_api_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_sub_account_api_key: Sub-Account API Key (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsAIPStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_sub_account_api_key', '_from', 'to']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method sub_account_stat_router_get_all_aggregated_ip_stats_for_a_sub_account" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_sub_account_api_key' is set
        if ('x_sub_account_api_key' not in params or
                params['x_sub_account_api_key'] is None):
            raise ValueError("Missing the required parameter `x_sub_account_api_key` when calling `sub_account_stat_router_get_all_aggregated_ip_stats_for_a_sub_account`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'to' in params:
            query_params.append(('to', params['to']))  # noqa: E501

        header_params = {}
        if 'x_sub_account_api_key' in params:
            header_params['X-SubAccount-ApiKey'] = params['x_sub_account_api_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/subaccount/stat/aggregate/ips', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ModelsAIPStat]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def sub_account_stat_router_get_all_aggregated_provider_stats_for_a_specific_ip_of_a_sub_account(self, x_sub_account_api_key, ipid, **kwargs):  # noqa: E501
        """sub_account_stat_router_get_all_aggregated_provider_stats_for_a_specific_ip_of_a_sub_account  # noqa: E501

        Get All Aggregated Provider Stats for a Specific IP of a Sub-Account  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.sub_account_stat_router_get_all_aggregated_provider_stats_for_a_specific_ip_of_a_sub_account(x_sub_account_api_key, ipid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_sub_account_api_key: Sub-Account API Key (required)
        :param int ipid: the IPId you want to get (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsPIPStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.sub_account_stat_router_get_all_aggregated_provider_stats_for_a_specific_ip_of_a_sub_account_with_http_info(x_sub_account_api_key, ipid, **kwargs)  # noqa: E501
        else:
            (data) = self.sub_account_stat_router_get_all_aggregated_provider_stats_for_a_specific_ip_of_a_sub_account_with_http_info(x_sub_account_api_key, ipid, **kwargs)  # noqa: E501
            return data

    def sub_account_stat_router_get_all_aggregated_provider_stats_for_a_specific_ip_of_a_sub_account_with_http_info(self, x_sub_account_api_key, ipid, **kwargs):  # noqa: E501
        """sub_account_stat_router_get_all_aggregated_provider_stats_for_a_specific_ip_of_a_sub_account  # noqa: E501

        Get All Aggregated Provider Stats for a Specific IP of a Sub-Account  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.sub_account_stat_router_get_all_aggregated_provider_stats_for_a_specific_ip_of_a_sub_account_with_http_info(x_sub_account_api_key, ipid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_sub_account_api_key: Sub-Account API Key (required)
        :param int ipid: the IPId you want to get (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsPIPStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_sub_account_api_key', 'ipid', '_from', 'to']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method sub_account_stat_router_get_all_aggregated_provider_stats_for_a_specific_ip_of_a_sub_account" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_sub_account_api_key' is set
        if ('x_sub_account_api_key' not in params or
                params['x_sub_account_api_key'] is None):
            raise ValueError("Missing the required parameter `x_sub_account_api_key` when calling `sub_account_stat_router_get_all_aggregated_provider_stats_for_a_specific_ip_of_a_sub_account`")  # noqa: E501
        # verify the required parameter 'ipid' is set
        if ('ipid' not in params or
                params['ipid'] is None):
            raise ValueError("Missing the required parameter `ipid` when calling `sub_account_stat_router_get_all_aggregated_provider_stats_for_a_specific_ip_of_a_sub_account`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ipid' in params:
            path_params['ipid'] = params['ipid']  # noqa: E501

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'to' in params:
            query_params.append(('to', params['to']))  # noqa: E501

        header_params = {}
        if 'x_sub_account_api_key' in params:
            header_params['X-SubAccount-ApiKey'] = params['x_sub_account_api_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/subaccount/stat/aggregate/ip/{ipid}/providers', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ModelsPIPStat]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def sub_account_stat_router_get_all_aggregated_provider_stats_for_a_sub_account(self, x_sub_account_api_key, **kwargs):  # noqa: E501
        """sub_account_stat_router_get_all_aggregated_provider_stats_for_a_sub_account  # noqa: E501

        Get All Aggregated Provider Stats for a Sub-Account  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.sub_account_stat_router_get_all_aggregated_provider_stats_for_a_sub_account(x_sub_account_api_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_sub_account_api_key: Sub-Account API Key (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsPIPStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.sub_account_stat_router_get_all_aggregated_provider_stats_for_a_sub_account_with_http_info(x_sub_account_api_key, **kwargs)  # noqa: E501
        else:
            (data) = self.sub_account_stat_router_get_all_aggregated_provider_stats_for_a_sub_account_with_http_info(x_sub_account_api_key, **kwargs)  # noqa: E501
            return data

    def sub_account_stat_router_get_all_aggregated_provider_stats_for_a_sub_account_with_http_info(self, x_sub_account_api_key, **kwargs):  # noqa: E501
        """sub_account_stat_router_get_all_aggregated_provider_stats_for_a_sub_account  # noqa: E501

        Get All Aggregated Provider Stats for a Sub-Account  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.sub_account_stat_router_get_all_aggregated_provider_stats_for_a_sub_account_with_http_info(x_sub_account_api_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_sub_account_api_key: Sub-Account API Key (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsPIPStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_sub_account_api_key', '_from', 'to']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method sub_account_stat_router_get_all_aggregated_provider_stats_for_a_sub_account" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_sub_account_api_key' is set
        if ('x_sub_account_api_key' not in params or
                params['x_sub_account_api_key'] is None):
            raise ValueError("Missing the required parameter `x_sub_account_api_key` when calling `sub_account_stat_router_get_all_aggregated_provider_stats_for_a_sub_account`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'to' in params:
            query_params.append(('to', params['to']))  # noqa: E501

        header_params = {}
        if 'x_sub_account_api_key' in params:
            header_params['X-SubAccount-ApiKey'] = params['x_sub_account_api_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/subaccount/stat/aggregate/providers', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ModelsPIPStat]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def sub_account_stat_router_get_all_sub_account_stats(self, x_sub_account_api_key, **kwargs):  # noqa: E501
        """sub_account_stat_router_get_all_sub_account_stats  # noqa: E501

        Get All Sub-Account Stats  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.sub_account_stat_router_get_all_sub_account_stats(x_sub_account_api_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_sub_account_api_key: Sub-Account API Key (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsRStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.sub_account_stat_router_get_all_sub_account_stats_with_http_info(x_sub_account_api_key, **kwargs)  # noqa: E501
        else:
            (data) = self.sub_account_stat_router_get_all_sub_account_stats_with_http_info(x_sub_account_api_key, **kwargs)  # noqa: E501
            return data

    def sub_account_stat_router_get_all_sub_account_stats_with_http_info(self, x_sub_account_api_key, **kwargs):  # noqa: E501
        """sub_account_stat_router_get_all_sub_account_stats  # noqa: E501

        Get All Sub-Account Stats  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.sub_account_stat_router_get_all_sub_account_stats_with_http_info(x_sub_account_api_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_sub_account_api_key: Sub-Account API Key (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsRStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_sub_account_api_key', '_from', 'to']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method sub_account_stat_router_get_all_sub_account_stats" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_sub_account_api_key' is set
        if ('x_sub_account_api_key' not in params or
                params['x_sub_account_api_key'] is None):
            raise ValueError("Missing the required parameter `x_sub_account_api_key` when calling `sub_account_stat_router_get_all_sub_account_stats`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'to' in params:
            query_params.append(('to', params['to']))  # noqa: E501

        header_params = {}
        if 'x_sub_account_api_key' in params:
            header_params['X-SubAccount-ApiKey'] = params['x_sub_account_api_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/subaccount/stat/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ModelsRStat]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def sub_account_stat_router_get_all_sub_account_stats_by_group(self, x_sub_account_api_key, group, **kwargs):  # noqa: E501
        """sub_account_stat_router_get_all_sub_account_stats_by_group  # noqa: E501

        Get All Sub-Account Stats by Group  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.sub_account_stat_router_get_all_sub_account_stats_by_group(x_sub_account_api_key, group, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_sub_account_api_key: Sub-Account API Key (required)
        :param str group: the tag whose stats you want (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsRStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.sub_account_stat_router_get_all_sub_account_stats_by_group_with_http_info(x_sub_account_api_key, group, **kwargs)  # noqa: E501
        else:
            (data) = self.sub_account_stat_router_get_all_sub_account_stats_by_group_with_http_info(x_sub_account_api_key, group, **kwargs)  # noqa: E501
            return data

    def sub_account_stat_router_get_all_sub_account_stats_by_group_with_http_info(self, x_sub_account_api_key, group, **kwargs):  # noqa: E501
        """sub_account_stat_router_get_all_sub_account_stats_by_group  # noqa: E501

        Get All Sub-Account Stats by Group  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.sub_account_stat_router_get_all_sub_account_stats_by_group_with_http_info(x_sub_account_api_key, group, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_sub_account_api_key: Sub-Account API Key (required)
        :param str group: the tag whose stats you want (required)
        :param str _from: from date
        :param str to: to date
        :return: list[ModelsRStat]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_sub_account_api_key', 'group', '_from', 'to']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method sub_account_stat_router_get_all_sub_account_stats_by_group" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_sub_account_api_key' is set
        if ('x_sub_account_api_key' not in params or
                params['x_sub_account_api_key'] is None):
            raise ValueError("Missing the required parameter `x_sub_account_api_key` when calling `sub_account_stat_router_get_all_sub_account_stats_by_group`")  # noqa: E501
        # verify the required parameter 'group' is set
        if ('group' not in params or
                params['group'] is None):
            raise ValueError("Missing the required parameter `group` when calling `sub_account_stat_router_get_all_sub_account_stats_by_group`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'to' in params:
            query_params.append(('to', params['to']))  # noqa: E501
        if 'group' in params:
            query_params.append(('group', params['group']))  # noqa: E501

        header_params = {}
        if 'x_sub_account_api_key' in params:
            header_params['X-SubAccount-ApiKey'] = params['x_sub_account_api_key']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/subaccount/stat/group', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ModelsRStat]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
